### ISSUE TITLE
Abillity to open any file from string (cloud)

### ISSUE THREAD

**Issue by lightenup** [equinor/dlisio#163]
- [ ] stream logical record #
- [ ] Bring your own IO (Support in find and read function-family)
- [ ] Support for d3 filehandle (and similar)

**Comment by ErlendHaa** [comment]
With dlisio now using lfp for io, this becomes mainly a task to implement a new lfp protocol
